services:
  postgres:
    image: postgres:16
    container_name: bank-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    volumes:
      - bank_pg_data:/var/lib/postgresql/data

volumes:
  bank_pg_data:
