# application-dev.yml
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: "bank_user"
    password: "01020304"
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
